version: "3"
services:
  frontend:
    container_name: frontend
    image: frontend:latest
    volumes:
      - '/node_modules'
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  backend:
    container_name: backend
    image: backend:latest
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/shop?serverTimezone=UTC&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root

  db:
    image: mysql:5.7
    container_name: db
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --skip-character-set-client-handshake
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shop
    volumes:
      - /home/db:/var/lib/mysql

  adminer:
   image: adminer
   ports:
      - "5000:8080"
